baseurl = "http://max.computer/"
theme = "cocoa-eh"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Max Veytsman"
title = "Max.Computer"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
copyright = "Copyright © 2012-2017 Max Veytsman"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = false
latestpostcount = 5
github = "mveytsman"
email = "maxim@ontoillogical.com"
linkedin = "max-veytsman-239a2432"
twitter = "mveytsman"
#social_banner = "img/banner.png"
posts_navigation = true

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
